DROP TABLE IF EXISTS user_ewm;

CREATE TABLE IF NOT EXISTS user_ewm (
    user_id bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title   varchar(255) NOT NULL,
    email   varchar(255) NOT NULL UNIQUE,

    CONSTRAINT user_ewm_title_not_blank CHECK (title NOT LIKE ' ' AND title NOT LIKE ''),
    CONSTRAINT user_ewm_email_not_blank CHECK (email NOT LIKE ' ' AND email NOT LIKE '')
);