version: '3.1'
services:
  stats-server:
    build: statistic-service/statistic-server/
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db/stat_prod
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6545:5432"
    environment:
      - POSTGRES_DB=stat_prod
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
